### ISSUE TITLE
Setup GH CLA assistant

### ISSUE THREAD

**Issue by elsalahy** [TheThingsIndustries/generic-node-se#107]
**Summary:** 

Setup [Github CLA](https://github.com/cla-assistant/cla-assistant) for the repo to manage contributors merges.

CC: @johanstokking 

**Why do we need this?**

To be able to merge external contributions.

**What is already there? What do you see now?**

Nothing

**What is missing? What do you want to see?**

A Github CLA to manage external contributions

**How do you propose to implement this?**

Setup the assistant.

**Environment:**

Github

**Acceptance Criteria:**

...

**What can you do yourself and what do you need help with?**

Didn't do it before, but can try.

**Comment by johanstokking** [comment]
Done
