### ISSUE TITLE
Add the TTC2021 videos in the documentation

### ISSUE THREAD

**Issue by wienke** [TheThingsIndustries/generic-node-se#112]
**Summary:** 
Add the TTC2021 videos in the documentation.

https://youtu.be/orhg0_kancg
https://youtu.be/Fxv1l75Ge1c
https://youtu.be/aHVi-FglC4Y
https://youtu.be/3ifZX8lO5Mg
...

**Why do we need this?**
Because they are very good
...

**What is already there? What do you see now?**
No videos yet.

**Comment by elsalahy** [comment]
This is done in https://github.com/TheThingsIndustries/generic-node-docs/pull/13, will close this after the PR is merged
