### ISSUE TITLE
Ninja is case sesitive

### ISSUE THREAD

**Issue by goran-mahovlic** [TheThingsIndustries/generic-node-se#118]
**Summary:** 
While testing docker run on linux following this guide

https://thethingsindustries.github.io/generic-node-docs/getting-started/se-sw/env-setup/docker/

this command is not working

`cmake -G ninja ../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=../../cross.cmake -DTARGET_APP=basic`

...

**How do you propose to implement this?**

Ninja seams to be case sensitive and this command is working.

`cmake -G Ninja ../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=../../cross.cmake -DTARGET_APP=basic`
...

**Comment by elsalahy** [comment]
Thanks @goran-mahovlic for the note, this is now fixed and updated in this [PR](https://github.com/TheThingsIndustries/generic-node-docs/pull/12)
