### ISSUE TITLE
Improve antenna performance

### ISSUE THREAD

**Issue by elsalahy** [TheThingsIndustries/generic-node-se#128]
**Summary:** 

The node RSSI is in the range of -80 to -90

**Steps to Reproduce:** 

1. Flash the node with `basic_lorawan` app
2. Record gateway, application logs

**What do you see now?**

Bad RSSI

Attached traced of SF12 and SF08.
The node is used without enclosure

[RSSI_SF08.txt](https://github.com/TheThingsIndustries/generic-node-se/files/6044682/RSSI_SF08.txt)
[RSSI_SF12.txt](https://github.com/TheThingsIndustries/generic-node-se/files/6044683/RSSI_SF12.txt)

**What do you want to see instead?**

Good RSSI in the range of -40 to -60

**How do you propose to implement this?**

Fix Antenna placement and tune accordingly.

**Environment:**

V1.1 PCB (second iteration, 100 patch)

**What can you do yourself and what do you need help with?**

I can provide assistance with Firmware configurations and testing.
@azerimaker needs to analyze other nodes and confirm if the issue is present and decide on a plan to fix this.

**Comment by elsalahy** [comment]
@marnixcrouzen can you please report the RSSI values of your node?

**Comment by marnixcrouzen** [comment]
> @marnixcrouzen can you please report the RSSI values of your node?

Did two readings, no casing, indoors
Reading 1:
  "time": "2021-02-26T12:32:45.181342063Z",
  "data_rate": "SF12BW125",
  "gateway 1":
      "rssi": -118,
  "gateway 2":
      "rssi": -109,
      "snr": 4.2,
Reading 2:
  "time": "2021-02-26T12:34:22.413363371Z",
  "data_rate": "SF10BW125",
  "gateway 1": 
      "rssi": -114,
      "snr": -0.8,
   "gateway 2":
      "rssi": -113,
      "snr": -0.2,

**Comment by elsalahy** [comment]
@marnixcrouzen thanks for confirming the issue.

**Comment by elsalahy** [comment]
@azerimaker please comment and update this issue, there seems to be a concern from the community as well observed in #163 

We need to update this in order to respond to community questions.

**Comment by elsalahy** [comment]
@azerimaker can you please update this issue with latest performance gains communicated by Ignion?

**Comment by azerimaker** [comment]
The design went through "Antenna Matching Network Tuning" process and we're happy to announce that it's efficiency have been improved quite significantly. Antenna has been tuned for various use cases and frequency ranges. Respective efficiency gains are shown below. 
![ignion-report](https://user-images.githubusercontent.com/2662257/124111416-8bfd8100-da69-11eb-86bd-de0e4d1f3a6e.PNG)

**Comment by azerimaker** [comment]
Closing this issue for now, but will repoen it once we have the second batch of nodes.
