### ISSUE TITLE
Simplify application configurations

### ISSUE THREAD

**Issue by elsalahy** [TheThingsIndustries/generic-node-se#133]
**Summary:** 

We need to make easy to configure the application layer functionalities.

**Why do we need this?**

To reduce the complexity of building an application with a specific configuration

**What is already there? What do you see now?**

Each app contains `app_conf.h` which enables and disables specific features.

**What is missing? What do you want to see?**

Open for discussion.
Could be:
- A GUI configurator
- A JSON based configurator similar to Mbed OS 
- A simple header file generator
- A simpler `app_conf.h`

**How do you propose to implement this?**

Discuss the options and purpose an example solution.

**Environment:**

BareMetal, OS based

**Acceptance Criteria:**

Should not affect applications targeted functionality

**What can you do yourself and what do you need help with?**

We need to discuss the possible options and I can implement the needed feature.

**Comment by azerimaker** [comment]
I've tested this new way of configuring the apps and it's way more intuitive than the previous versions. Good work, @elsalahy .

**Comment by NicolasMrad** [comment]
any updates here?

**Comment by azerimaker** [comment]
We already have the _app_conf.h_ configuration file in place and it does the job. As of now a GUI configurator is out of scope, but we can revisit this topic.
