### ISSUE TITLE
Add basic GNSE_Sleep function template

### ISSUE THREAD

**Issue by marnixcro** [TheThingsIndustries/generic-node-se#139]
**Summary:** 

Currently, setting the GNSE to sleep can be achieved by calling multiple functions. To make this easier, a high level API call should be available for users to implement.

**Why do we need this?**

To improve readability of one of the most important aspects of the GNSE.

**What is already there? What do you see now?**

Low level functions for sleeping.

**What is missing? What do you want to see?**

One (or several) high level Sleep function.

**How do you propose to implement this?**

- Create interface for sleep functionality.

**Environment:**

Baremetal

**Acceptance Criteria:**

- All apps compile without warning
- The sleep function(s) show expected behaviour

**What can you do yourself and what do you need help with?**

All

**Comment by elsalahy** [comment]
This is covered in #205
