### ISSUE TITLE
Adding basic examples (RGB blink, LoRaWAN TH sensor app)

### ISSUE THREAD

**Issue by azerimaker** [TheThingsIndustries/generic-node-se#141]
**Summary:** 

I needed basic test codes for testing the board functionality, therefore I copied  the `basic` and the `basic_lorawan` examples into `basic_blink` and `basic_lorawan_th` and added required functionalities, while remodeling the unnecessary ones. 

**Why do we need this?**

`basic_blink` is needed to serve as a barebones project to start with. 
`basic_lorawan_th` is needed to run real-world tests on the nodes.

**What is already there? What do you see now?**

The  `basic` and the `basic_lorawan` examples are great for testing the basic board functionality but didn't serve the purpose. 

**What is missing? What do you want to see?**

Having a barebones (template project) for starting new project. 

**How do you propose to implement this?**

`basic_blink` serves as a barebones project. Many of the test functions have been removed from the main, but the code have been kept in case someone wants to add only the necessary readings. 

**Environment:**

Baremetal. 

**Acceptance Criteria:**

- All basic application compile without warnings.
- Sensor reading code is a bit hacky, but does the job for now.

**What can you do yourself and what do you need help with?**

@elsalahy, @marnixcro please take a look at the `basic_lorawan_th` branch and let me know if anything need to be changed.

**Comment by elsalahy** [comment]
@azerimaker I think instead of calling it basic_blink, I recommend creating a an app called `template`
and for temperature humidity app, I think #178 will cover the same functionality
