### ISSUE TITLE
Improve silkscreen font and layouts and logo

### ISSUE THREAD

**Issue by elsalahy** [TheThingsIndustries/generic-node-se#146]
**Summary:** 

@azerimaker  will add more on the issue and we can ask someone for design feedback

**Comment by azerimaker** [comment]
Current revision (1.1b) this issue has been fixed.

**Comment by azerimaker** [comment]
@NicolasMrad that's what we will do with the next batch.

**Comment by NicolasMrad** [comment]
can this be closed?

**Comment by azerimaker** [comment]
@NicolasMrad thank you for closing this as well.
