### ISSUE TITLE
Create Enclosure visuals (front/back labels)

### ISSUE THREAD

**Issue by elsalahy** [TheThingsIndustries/generic-node-se#149]
**Summary:** 

Generic Node (SE) needs a professional front and back labels. On the front side we have a 2mm opening for the RGB LED and 8mm opening for the user button. Those will be covered with a outdoor resistant embossed sticker. 
On the back side we can add some certification, serial number and QR claiming information. 

**Why do we need this?**
We need more polished version of the front and back labels. 

**What is already there? What do you see now?**
Created a rough version of the front panel (10x scaled) for the early prototypes, but we need more professional version. 
[GNSEv1.1_front_panel_scale_10x_label.pdf](https://github.com/TheThingsIndustries/generic-node-se/files/6207186/GNSEv1.1_front_panel_scale_10x_label.pdf)

**What is missing? What do you want to see?**
I've added the dimensions below, having a unique front panel design and more generic back panel would be really beneficial.

**Comment by wienke** [comment]
@pierrephz for the Generic Node we need a design for the top and bottom of the device:

* Top - clean visual and there is a button position somewhat at the center.
* Bottom - this should have our company info, CE mark, place for a QR code. And an instruction where people can scan it. Use tti.fyi/qr for now.

**Comment by azerimaker** [comment]
@pierrephz I've added dimensions for the front/back panel visuals. Please use this as a reference. 

[GNSEv1.1_label_dimensions.pdf](https://github.com/TheThingsIndustries/generic-node-se/files/6207153/GNSEv1.1_label_dimensions.pdf)

**Comment by pierrephz** [comment]
@azerimaker please can you send me the final content/info, CE mark, QR code, etc. when you have it?

**Comment by azerimaker** [comment]
@pierrephz hopefully next month we'll have a right to use the CE marking, in the meantime you can already start the design using this resources: 
https://ec.europa.eu/growth/single-market/ce-marking_en
 
Please note that the CE marking must be **no smaller than** **5mm.**

**Comment by azerimaker** [comment]
We've picked [this ](https://drive.google.com/file/d/1XM6PYIHjcL4YFFjKD1V_C2ZlUPKB8d2l/view?usp=sharing)design and it will be screen printed with UV resistant color and glue. 
![frontlabel](https://user-images.githubusercontent.com/2662257/124457960-b5c9e700-dd8c-11eb-8b17-4ab24625075d.PNG)
