### ISSUE TITLE
Freefall Downlink LoRaWAN example

### ISSUE THREAD

**Issue by marnixcro** [TheThingsIndustries/generic-node-se#156]
**Summary:** 

There should be a application utilising downlinks as a feature. The freefall app is a good example for this, as it has a use case for finding the dropped GNSE with small beeps.

**Why do we need this?**

No such app exist yet, but user might still have need of this in their applications (using as remote warnings after data was processed on the server). Providing an example that can already separate the messages based on port and the content could help these users to quickly start their own implementations.

**What is already there? What do you see now?**

No apps with implemented downlinks.

**What is missing? What do you want to see?**

Freefall app with downlink.

**How do you propose to implement this?**

Add a basic downlink handler in freefall app for user defined actions.

**Environment:**

Baremetal

**Acceptance Criteria:**

Downlinks can be utilised in an application, no errors/warnings.

**What can you do yourself and what do you need help with?**

All

**Comment by elsalahy** [comment]
@marnixcro 
basic LoRaWAN already provides sufficient downlink functionality by switching to call B and C, so please avoid changing this app.

Your suggested feature can be done as part of the example application like the freefall app, for example activating the buzzer and LED via a downlink to identify the object that has free-fallen
