### ISSUE TITLE
Antenna Performance w/ and w/o enclosure.

### ISSUE THREAD

**Issue by ehogeweg** [TheThingsIndustries/generic-node-se#163]
Hi,

I noticed that the enclosure screws are close to the antenna clearance area. I expect this has some impact on the tuning frequency. Is there any data, that you can share, on how the antenna performs on a bare board vs. enclosed? Does the matching network require different component?

Cheers,

Erwin

**Comment by azerimaker** [comment]
Thank you for you interest, @ehogeweg. 
I understand your concern. In fact, we've discussed this even before we had the PCBs at hand in issues #89, #128. 
The enclosure and the close proximity of the screws has certainly some impact on the ANT performance, however we don't have any comparison data or quantitative info on that at this moment. 
We're working on it and once we have it, I'll share our findings here.

**Comment by azerimaker** [comment]
@ehogeweg , @lnlp I did a basic efficiency test using my NanoVNA. Please see the results here ➡️  https://github.com/TheThingsIndustries/generic-node-se/issues/89#issuecomment-833003749
You're right, the enclosure and the batteries do affect the antenna performance and removing it results in shifting the tuning frequency upwards. In the coming weeks the device will go through proper matching network retuning. Hopefully, this will provide good performance with the enclosure on.

**Comment by elsalahy** [comment]
@azerimaker did Ignion provide any feedback on the effect of the enclosure on the antenna performance?

**Comment by azerimaker** [comment]
> @azerimaker did Ignion provide any feedback on the effect of the enclosure on the antenna performance?

unfortunately their "Matching Network Optimization" service doesn't include that, but I will ask them to perform those tests, hopefully they agree to that.

**Comment by azerimaker** [comment]
@lnlp Ignion has conducted the above mentioned tests and it's clear that frequency shift is major. One should use the device as a fully assembled unit if they want to achieve good coverage.  I hope this answers your question. If there are no further discussion, please consider closing this issue. 

![image002](https://user-images.githubusercontent.com/2662257/124727312-e33e9e00-df0e-11eb-8af9-7cf74a2ea85e.png)

![image001](https://user-images.githubusercontent.com/2662257/124727303-e20d7100-df0e-11eb-9e5f-02e82827a5f5.png)

**Comment by azerimaker** [comment]
> For positioning of the device it will be interesting to know the radiation pattern and how the device can be best positioned for optimal RF coverage/range. _(The battery holder and batteries will block, reflect and deflect RF signals.)_

Unlike anticipated the batteries and the contacts didn't have major impact on the antenna performance and its radiation pattern. Please see the results below for your reference. 
 
![rad-1](https://user-images.githubusercontent.com/2662257/124727967-7d064b00-df0f-11eb-96ad-308539eb902c.PNG)
![rad-2](https://user-images.githubusercontent.com/2662257/124727979-80013b80-df0f-11eb-9038-38a54360854a.PNG)
![rad-3](https://user-images.githubusercontent.com/2662257/124727990-82639580-df0f-11eb-80e0-92b9a45e7834.PNG)

**Comment by elsalahy** [comment]
@ehogeweg  Does the above answer provide sufficient information for GNSE use with an enclosure.
If yes, could you please the issue

**Comment by ehogeweg** [comment]
Sorry, I completely missed your comments. Yes, this answers the question. Thanks for providing the graphs.

Cheers,

Erwin
