### ISSUE TITLE
Improve freefall_lorawan power settings

### ISSUE THREAD

**Issue by marnixcro** [TheThingsIndustries/generic-node-se#180]
**Summary:** 

Currently the free fall app consumes ~100 uA in its sleep mode. This can be lowered by utilising the power modes correctly with the free fall detection. The lowest power consumption should also be tested and documented.

**Why do we need this?**

To lower power consumption and give an for the free fall app's power consumption.

**What is already there? What do you see now?**

Working free fall application with ~100 uA current consumption. Turning off the load switch reduces this to ~2 uA (similar to basic_lorawan). No power optimisations where implemented yet with the design.

**What is missing? What do you want to see?**

Improved settings for the LIS2DH12 free fall initialisation and an indication of the possible power consumption of the free fall application.

**How do you propose to implement this?**

- Lower the ODR and test if free fall detection still works.
- Activate the lowest power mode that still support free fall detection.
- Set the other peripherals (SHTC3 and ATECC608A) in the most optimal low power mode if possible (for testing purposes)

**Environment:**

Bare metal

**Acceptance Criteria:**

Lowered power consumption on the GNSE.

**What can you do yourself and what do you need help with?**

This issue is only for the free fall application power settings and testing how far it can go into low power mode. Issue #171 relates to the actual low power manager for the peripherals (including the LIS2DH12).

**Comment by elsalahy** [comment]
Blocked on #171
