### ISSUE TITLE
Mbed LoRaWAN example

### ISSUE THREAD

**Issue by marnixcr** [TheThingsIndustries/generic-node-se#182]
**Summary:** 

Add an application utilising LoRaWAN and Mbed OS.

**What is already there? What do you see now?**

LoRaWAN examples with FreeROTS, AzureRTOS and bare metal.

**What is missing? What do you want to see?**

Mbed OS integration with LoRaWAN.

**How do you propose to implement this?**

A [LoRaWAN example](https://github.com/ARMmbed/mbed-os-example-lorawan) and [STM32WL support](https://github.com/ARMmbed/mbed-os/tree/master/targets/TARGET_STM/TARGET_STM32WL) already exist. These, with additional pin mapping and GNSE firmware, should be integrated into an application for LoRaWAN.

**Environment:**

Mbed

**Acceptance Criteria:**

Application with Mbed works with LoRaWAN.

**What can you do yourself and what do you need help with?**

All

**Comment by marnixcro** [comment]
Issue was fixed in the (private) GNSE OS mbed firmware application. [Standard LoRaWAN example](https://github.com/ARMmbed/mbed-os-example-lorawan) can work as well.

**Comment by elsalahy** [comment]
Still in review, moving this to Q3

**Comment by NicolasMrad** [comment]
any updates here?

**Comment by azerimaker** [comment]
Not much, please see the other comment.
