### ISSUE TITLE
Broken multicast support (McRootKey is always generated based on LoRaWAN version 1.1.0 scheme)

### ISSUE THREAD

**Issue by elsalahy** [TheThingsIndustries/generic-node-se#196]
**Summary:** 

Our current LoRaWAN stack generates the MC keys based on 1.1 even when configured for 1.0.3

This is a mirror of an already fixed issue on LMN version 4.4.5

https://github.com/Lora-net/LoRaMac-node/issues/936

**Comment by elsalahy** [comment]
@johanstokking we use an ST LoRaWAN stack that is based on LMN v4.4.4

A lot of critical fixes related to FUOTA and LoRaWAN have been done since then as you can see from the [change log](https://github.com/Lora-net/LoRaMac-node/blob/master/CHANGELOG.md)

Should I just keep patching our current stack?
The issue mentioned above wasted a lot of my effort o debug and identify the root cause.

**Comment by johanstokking** [comment]
> Should I just keep patching our current stack?

What is the alternative? Switch to LMN and add ST support ourselves?

**Comment by elsalahy** [comment]
> What is the alternative? Switch to LMN and add ST support ourselves?

Yes
This approach also has it's disadvantages, but it pays out in the long term.

As a short term solution I can keep patching the current ST version until they fix it them selves.

**Comment by johanstokking** [comment]
What is the balance in terms of effort between to these two approaches?

1. Take vanilla LMN and add ST support
2. Take ST LMN and patch upstream changes

**Comment by johanstokking** [comment]
OK, then I'm in favor of going with taking the vanilla LMN and add ST support.

Until, of course, ST publishes a stable version that covers our use cases. I don't see this happening in the short term, especially not with LoRaWAN 1.0.4 and 1.1.1 coming up.

**Comment by elsalahy** [comment]
Thanks @johanstokking.
I will plan this accordingly.
