### ISSUE TITLE
Sensors_lorawan gets stuck without debugger due to uninitialized ADC

### ISSUE THREAD

**Issue by marnixcr** [TheThingsIndustries/generic-node-se#221]
**Summary:** 

Sensors_lorawan gets stuck when the debugger is turned off due to the ADC not being reinitialised after stop mode.

**Steps to Reproduce:** 

1. Set [DEBUGGER_ON](https://github.com/TheThingsIndustries/generic-node-se/blob/df1c9b8dd9652ac8cc39db01d5674b4eebca0572/Software/app/sensors_lorawan/conf/app_conf.h#L31) in sensors_lorawan to 0.

**What do you see now?**

The application gets stuck after the join procedure.

**What do you want to see instead?**

Sensors_lorawan running without getting stuck.

**How do you propose to implement this?**

Initialise the ADC [here](https://github.com/TheThingsIndustries/generic-node-se/blob/df1c9b8dd9652ac8cc39db01d5674b4eebca0572/Software/app/sensors_lorawan/sys_app.c#L81).

**Environment:**

Bare metal

**What can you do yourself and what do you need help with?**

All

**Comment by elsalahy** [comment]
This should be fixed in #208, otherwise we can re-open it
