### ISSUE TITLE
Better enclosure screws

### ISSUE THREAD

**Issue by elsalahy** [TheThingsIndustries/generic-node-se#229]
**Summary:** 

Can we investigate if the enclosure screws material can be changed to something that is more durable.
The current enclosure screws can't handle the screw driver pressure and tend to have edge deformity if screwed and unscrewed multiple times.

CC: @wienke and @azerimaker

**Comment by NicolasMrad** [comment]
@azerimaker did you test out the durability of the screws?

**Comment by azerimaker** [comment]
@NicolasMrad current screws are the default ones supplied by the manufacturer and after various mechanical torture testing they seem to hold OK. I don't see a reason to upgrade them right now.
