### ISSUE TITLE
MIC Mismatch error over-and-over while redoing TTN Amsterdam Workshop follow-up 

### ISSUE THREAD

**Issue by BRUNO7878** [TheThingsIndustries/generic-node-se#246]
Hi Orkhan,

**Summary:** 
I try to redo the TTN Amsterdam workshop on connecting  the generic node to the TTIG gateway
Unfortunately I get "MIC mismatch" error is generated.

**Steps to Reproduce:** 

1. Create TTS cloud account
2. Set up the gateway TTIG868 ( this seems to work as I see it in the console
3. Add Application in the console
4. Add Device in the application ( QR code does not work => Manual ) 
5. Missing the exact set up ( as described in the workshop of Friday ) 
The observed the MIC Mismatch 
![End device set up ](https://user-images.githubusercontent.com/38864469/192148386-0c8c0f4a-7d5c-4e16-9fa9-c9ad890fa6f2.jpg)

7. ...

**What do you see now?**
{
  "name": "ns.up.join.cluster.fail",
  "time": "2022-09-25T14:11:48.996779017Z",
  "identifiers": [
    {
      "device_ids": {
        "device_id": "eui-0004a310001ab086",
        "application_ids": {
          "application_id": "my-cellar-conditions"
        },
        "dev_eui": "0004A310001AB086",
        "join_eui": "70B3D57ED0000000"
      }
    }
  ],
  "data": {
    "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
    "namespace": "pkg/joinserver",
    "name": "mic_mismatch",
    "message_format": "MIC mismatch",
    "correlation_id": "0bd7bf72259542f49025b4279cbab2f4",
    "code": 3
  },
  "correlation_ids": [
    "ns:uplink:01GDTFTV3TNSNYA59KMRME0WJB",
    "pba:conn:up:01GCVC8DZ97A0SDB61H0E8QFZ4",
    "pba:uplink:01GDTFTV3Q4XFTN6VB9X27Y9XN",
    "rpc:/ttn.lorawan.v3.GsNs/HandleUplink:01GDTFTV3TG27N3314826FTF0E"
  ],
  "origin": "ip-10-23-6-193.eu-west-1.compute.internal",
  "context": {
    "tenant-id": "CgRnbnNl"
  },
  "visibility": {
    "rights": [
      "RIGHT_APPLICATION_TRAFFIC_READ"
    ]
  },
  "unique_id": "01GDTFTV44KDTQC9XZ09DW2MZ4"
}

**Environment:**
Set up on MAC book pro,
Following training guide lines 

...

**What can you do yourself and what do you need help with?**
Is its mandatory to make a device claim ? If so where is this explained ?
What is a tenant ?
Do you have a more complete slide deck to explain the steps ( without QR code  ) to have the "plain vanilla" set-up connected to a private gateway ??
There is no YouTube video showing a successful step-by-step genericnode connection .
When would this one be published ?
Instead the is a long traning about hardware and FW dev .
Note : that the AppEUI provided on the Generic node is 1 char too short vs what the console is expecting .
After several trials and errors Have been looking at the training slide deck => I guessed from slide 16 it was to append a "0" at the end.

Thank you for your support

**Comment by azerimaker** [comment]
Closing this issue, as it was already resolved in a debug call with @BRUNO7878 .
