### ISSUE TITLE
DC/DC Converters RP605Z283B available

### ISSUE THREAD

**Issue by peterl3233** [TheThingsIndustries/generic-node-se#247]
Given that there are chip shortages; I have 6 pieces of new and unused, unopened, RP605Z283B.  Anyone is welcome to them so long as there are no export controls.  I'd ask that you cover my original costs plus mail.

**Comment by azerimaker** [comment]
Hi @peterl3233 . Looks like stock situation is OK now with this part. If you don't mind I'm closing this issue for now.
