### ISSUE TITLE
High current consumption in "stop mode" 

### ISSUE THREAD

**Issue by ThomasBaumgartner** [TheThingsIndustries/generic-node-se#248]
**Summary:** 

I configured the application with lowpower options. I connected power analyser to the device (Generci Noce V1.1)and measured current consumption during stop mode. The power analyser was indicating a minimum current consumption of 33uA, which is rather high.  

**Steps to Reproduce:** 

1. In app_conf.h set: 
GNSE_ADVANCED_TRACER_ENABLE 0
DEBUGGER_ON       0

2. build and flash sensors_lorawan application
3. Measure the current consumption

**What do you see now?**

Minimum current consumption of 33uA, normal current consumption during join / send procedure.

**What do you want to see instead?**

A minimum current consumption of <5uA.

Has anybody experienced similar behaviour? Anybody able to have lower current consumption in low power mode? 
 @azerimaker

**Comment by azerimaker** [comment]
Hi, @ThomasBaumgartner 

thank you for raising this issue. The extra ~31uA is usually the result of the battery monitor circuit being left ON. This was a minor bug which was addressed in the `sensors_lorawan_se` app. Please refer to [Software/app/sensors_lorawan_se/sensors.c](https://github.com/TheThingsIndustries/generic-node-se/commit/532066aa9d1b59a6e9d9434ae63ec6c2640ed7a8) to make sure your code follows the same sequence and let us know the results.
I hope it helps.

**Comment by ThomasBaumgartner** [comment]
Hi @azerimaker 

Thank you for your answer. Disabling the battery monitor circuit solved the issue. With this modification the device reaches a current consumption in stop mode of 2.4uA.

**Comment by azerimaker** [comment]
Happy to help, @ThomasBaumgartner .

**Comment by ThomasBaumgartner** [comment]
I further recommend removing the GNSE_BSP_BM_Enable(); on line 34 in sensors.c in the function sensors_init() to reduce the current consumtion also between joining and first message transmission.
