### ISSUE TITLE
Generic Node SE Edition on AU915 band

### ISSUE THREAD

**Issue by ingmanuelalfonso** [TheThingsIndustries/generic-node-se#249]
**Summary:** 
I am testing for the first time the Generic Node SE and found that using the provided libraries something is wrong when tryed the AU915 band. The device came with EU868 but its possible to enable US915 but not AU915. Someone else had this problem?. 

...

**Steps to Reproduce:** 

1. ... Using STM32CUBE IDE and using basic_lorawan example
2. ... On lora_app.h edited ACTIVE_REGION to LORAMAC_REGION_AU915
3. ... In lora_info.c the REGION_AU915 is in gray color as other bands.

I noted that is possible to disolder hardware components that goes to Ceramic Antena and solder ones to go to the external antenna connector but sure this is not the problem

**Comment by azerimaker** [comment]
Please make sure you add the -DREGION_AU915="ON" flag on you cmake. Please try this and let us know: 

`cmake -G "MinGW Makefiles" ../.. -DCMAKE_BUILD_TYPE=Debug -DREGION_AU915="ON" -DCMAKE_TOOLCHAIN_FILE=../../cross.cmake -DTARGET_APP=basic_lorawan`

If the gateways is not too far, you don't need to perform any changes to the matching network of the antenna. It will work in AU915 band as well.

**Comment by ingmanuelalfonso** [comment]
I came back to the same topic to inform I am able to communicate using AU915. 

- I am using sensors_lorawan App example
- I am using Chirpstack 3.0 as a network and application server
- I am using OTAA.
- I am using RAk7271 8 channel gateway connected to a raspberry pi 3b+

**Comment by azerimaker** [comment]
Thank you for the update, @ingmanuelalfonso.
