### ISSUE TITLE
System Wide control APIs

### ISSUE THREAD

**Issue by elsalahy** [TheThingsIndustries/generic-node-se#57]
**Summary:** 

We need to have a system wide control APIs that allow us to 
- Initialize the system clock
- Initialize the system debug interfaces
- Initialize relevant sensors
- Handle multiple error levels based on the severity of the error.

**Why do we need this?**

To avoid code replication and follow the DRY principle in the application development.

**What is already there? What do you see now?**

BSP & HAL control of the device components.

**What is missing? What do you want to see?**

High level APIs that initialize the system based on a set of configurations passed from application layer.

**How do you propose to implement this?**

Handle each component separately and define and implement the affiliate functions:

- System Initialization 
- System Erros
- System Debugging

**Environment:**

Baremetal

**Acceptance Criteria:**

- All Applications compile and function as intended before the new system wide changes.

**What can you do yourself and what do you need help with?**
ALL

**Comment by elsalahy** [comment]
Sensor on board components HAL is covered as part of #73

**Comment by marnixcro** [comment]
For the current status of the APIs and new names:

- Clock Function would be something like GNSE_BSP_CLK_Init, with the content being the configuration present currently in all applications.
- Debug interface name would be GNSE_BSP_DBG_Init. Like with the clocks, all applications currently redefine DBG_Init without any changes between them.
- Sensors are already done in #73, as was mentioned previously
- Error levels were sort of updated with #159 with the verbosity being configurable with simple function calls. Low verbosity could still be added to this.

**Comment by elsalahy** [comment]
Ok some notes:
- For the clock it should be `GNSE_HAL` and not `GNSE_BSP`
-`DBG_Init()` will be handled by the LPM since it relates to using the debugger in low power.

**Comment by elsalahy** [comment]
This issue is implemented in #73, #171 and #207 
For further improvements we should open new smaller issues.
