### ISSUE TITLE
Potential ANT performance issue

### ISSUE THREAD

**Issue by azerimaker** [TheThingsIndustries/generic-node-se#89]
**Summary:** 

In their first layout review Fractus has mentioned to place the antenna on the back side of the mainboard. 
As can be seen from the review, we followed all their design recommendations, but one. To simplify the manufacturing and bring more prominence for the component I've placed it on the front side of the board.  Now that the component is slightly closer to battery contacts, which might result in slightly degraded RF performance and Fractus is a bit concerned about this. 
![ant1](https://user-images.githubusercontent.com/2662257/102076336-dbe76400-3e07-11eb-86d4-13f3cc7040e6.png)

**Next step:** 

Once we have the first prototypes, I'll do in-depth testing to compare the performance penalty. 
If the performance is severely degraded, I'll place the antenna on the back side (as shown below).
![ant3](https://user-images.githubusercontent.com/2662257/102076535-21a42c80-3e08-11eb-98d9-4e101971f2d1.jpg)
![ant-2](https://user-images.githubusercontent.com/2662257/102076538-223cc300-3e08-11eb-80f9-321d905a6fd0.jpg)

**Comment by azerimaker** [comment]
I did a crude antenna return loss (efficiency) and VSWR measurements with my NanoVNA. 
Without any matching network tuning antenna works best for **938MHz** with VSWR value of **~1.73** inside the fully assembled enclosure. Without the enclosure frequency shifts to **~960MHz** with VSWR value of **~1.04**. The antenna clearly performs better without the enclosure, but once it goes through matching network retuning with the enclosure we can get good performance out of it. 

**Test with the enclosure:**
![nano-vna-test](https://user-images.githubusercontent.com/2662257/117207911-ce516b80-adf4-11eb-879b-b0b0f2d6797d.PNG)

**Test without the enclosure:**
![nano-vna-wo-enclosure](https://user-images.githubusercontent.com/2662257/117208459-7109ea00-adf5-11eb-99d1-1d0e18a65eb5.PNG)

**Comment by elsalahy** [comment]
This issue is part of Q2,  do we have any progress on this?

**Comment by azerimaker** [comment]
As suspected overlapping battery terminals on the ANT clearance area does slightly reduce the efficiency, but after we've gone through the matching network retuning on the actual device it became evident that the real device performs better than the simulated results. Please see #128 for more info.
